"""Init database

Revision ID: 3d9ad78cf26a
Revises: 
Create Date: 2021-06-25 14:32:33.621749

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3d9ad78cf26a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polls',
                    sa.Column('id', sa.String(length=40), nullable=False),
                    sa.Column('title', sa.String(length=500), nullable=False),
                    sa.Column('creator_id', sa.String(length=40), nullable=False),
                    sa.Column('type', sa.String(length=40), nullable=False),
                    sa.Column('allow_add_choice', sa.Boolean(), nullable=True),
                    sa.Column('allow_multiple_choice', sa.Boolean(), nullable=True),
                    sa.Column('end_at', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.BigInteger(), nullable=True),
                    sa.Column('updated_at', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_votes',
                    sa.Column('vote_id', sa.String(length=40), nullable=False),
                    sa.Column('user_id', sa.String(length=40), nullable=False),
                    sa.Column('created_at', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('vote_id', 'user_id')
                    )
    op.create_table('votes',
                    sa.Column('id', sa.String(length=40), nullable=False),
                    sa.Column('title', sa.String(length=500), nullable=False),
                    sa.Column('creator_id', sa.String(length=40), nullable=False),
                    sa.Column('image', sa.String(length=500), nullable=True),
                    sa.Column('last_user_update', sa.String(length=40), nullable=False),
                    sa.Column('poll_id', sa.String(length=40), nullable=False),
                    sa.Column('count', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.BigInteger(), nullable=True),
                    sa.Column('updated_at', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id', 'poll_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('user_votes')
    op.drop_table('polls')
    # ### end Alembic commands ###
